"""
sentinel/schema.py

Core trace data model for the Sentinel SDK.
This is the contract between the SDK (Module 1) and the Ingest API (Module 2).
Do not change field names or types without coordinating with the ingest API engineer.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class Environment(str, Enum):
    PROD = "prod"
    STAGING = "staging"
    DEV = "dev"


class SignalType(str, Enum):
    THUMBS_DOWN = "thumbs_down"
    ESCALATE = "escalate"
    REPHRASED = "rephrased"
    ABANDONED = "abandoned"
    ACKNOWLEDGED = "acknowledged"


# ---------------------------------------------------------------------------
# Sub-models
# ---------------------------------------------------------------------------

class ContextDocument(BaseModel):
    """A single retrieved document injected into the LLM context."""
    content: str = Field(..., description="Full text of the retrieved chunk")
    source: str = Field(..., description="Origin identifier, e.g. 'policy_doc_v3.pdf', 'kb://article-42'")
    score: Optional[float] = Field(None, description="Retrieval relevance score if available")


class ToolCall(BaseModel):
    """A single tool call made by the LLM during the trace."""
    tool_name: str = Field(..., description="Name of the tool as registered in the system")
    input: dict[str, Any] = Field(..., description="Arguments passed to the tool")
    output: Optional[Any] = Field(None, description="Result returned by the tool")
    error: Optional[str] = Field(None, description="Error message if tool call failed")
    latency_ms: Optional[int] = Field(None, description="Time taken for the tool call in milliseconds")


class TokenCounts(BaseModel):
    """Token usage for the LLM call."""
    prompt: int = Field(..., ge=0)
    completion: int = Field(..., ge=0)
    total: int = Field(..., ge=0)

    @field_validator("total")
    @classmethod
    def total_must_match(cls, v: int, info: Any) -> int:
        prompt = info.data.get("prompt", 0)
        completion = info.data.get("completion", 0)
        if v != prompt + completion:
            raise ValueError(f"total ({v}) must equal prompt ({prompt}) + completion ({completion})")
        return v


class MessageTurn(BaseModel):
    """A single turn in the conversation history."""
    role: str = Field(..., description="'user', 'assistant', or 'system'")
    content: str


# ---------------------------------------------------------------------------
# Core trace model
# ---------------------------------------------------------------------------

class TracePayload(BaseModel):
    """
    The complete record of one LLM inference call.

    Generated by the SDK at the point of capture and shipped async to the
    Sentinel ingest API. This model is the single source of truth for the
    trace schema across all modules.
    """

    # --- Identity ---
    trace_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="UUID generated client-side. Unique per inference call."
    )
    customer_id: str = Field(
        ...,
        description="Derived from the customer's Sentinel API key."
    )
    session_id: str = Field(
        ...,
        description="Groups all traces belonging to one user conversation."
    )
    user_id: Optional[str] = Field(
        None,
        description="Optional. Customer-provided identifier for the end user."
    )

    # --- Routing metadata ---
    flow_name: str = Field(
        ...,
        description="Logical name for the AI flow, e.g. 'support', 'sales', 'onboarding'."
    )
    environment: Environment = Field(
        default=Environment.PROD,
        description="Deployment environment this trace was captured in."
    )

    # --- Model ---
    model_name: str = Field(
        ...,
        description="Model identifier as returned by the provider, e.g. 'gpt-4.1', 'claude-sonnet-4-6'."
    )
    model_version: Optional[str] = Field(
        None,
        description="Specific version or snapshot string if available from the provider."
    )

    # --- Conversation ---
    user_prompt: str = Field(
        ...,
        description="The most recent user message that triggered this inference call."
    )
    message_history: list[MessageTurn] = Field(
        default_factory=list,
        description="Full conversation history preceding this call, oldest first."
    )

    # --- Retrieval ---
    retrieved_context: list[ContextDocument] = Field(
        default_factory=list,
        description="Documents injected into context via RAG. Empty list if no retrieval."
    )

    # --- Response ---
    llm_response: str = Field(
        ...,
        description="The full text response generated by the LLM."
    )

    # --- Tool calls ---
    tool_calls: list[ToolCall] = Field(
        default_factory=list,
        description="All tool calls made during this inference, in order. Empty if none."
    )

    # --- Performance ---
    latency_ms: int = Field(
        ...,
        ge=0,
        description="Total wall-clock time from API call to response received, in milliseconds."
    )
    token_counts: TokenCounts = Field(
        ...,
        description="Prompt, completion, and total token counts for this call."
    )

    # --- Timestamp ---
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of when the trace was captured by the SDK."
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "trace_id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                "customer_id": "cust_abc123",
                "session_id": "sess_xyz789",
                "user_id": "user_42",
                "flow_name": "support",
                "environment": "prod",
                "model_name": "gpt-4.1",
                "model_version": None,
                "user_prompt": "Can I get a refund after 40 days?",
                "message_history": [
                    {"role": "user", "content": "Hi, I need help with my order."},
                    {"role": "assistant", "content": "Of course! What can I help you with?"}
                ],
                "retrieved_context": [
                    {
                        "content": "Refunds are only allowed within 30 days of purchase.",
                        "source": "refund_policy_v2.pdf",
                        "score": 0.94
                    }
                ],
                "llm_response": "Yes, you can request a refund.",
                "tool_calls": [],
                "latency_ms": 843,
                "token_counts": {"prompt": 312, "completion": 18, "total": 330},
                "timestamp": "2026-06-09T10:30:00Z"
            }
        }
    }


# ---------------------------------------------------------------------------
# Behavioral signal model (used by SDK-03)
# ---------------------------------------------------------------------------

class SignalPayload(BaseModel):
    """
    Lightweight user behavior signal sent after a trace.
    Ships separately from the full TracePayload via the same async shipper.
    """
    signal_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    trace_id: str = Field(..., description="The trace this signal is associated with.")
    customer_id: str
    signal_type: SignalType
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))